name: retrofit
channels:
  - conda-forge
  - patrikhlobil
dependencies:
  - ipykernel
  - ploomber
  - pandas-bokeh
  - geopandas
  - seaborn
  - python-dotenv
  - requests
  - aiohttp

  - pip
  - pip:
    - rcbm
    - codema-dev-tasks==0.2.0 