name: estimate-commercial-energy-via-valuation-office-floor-areas
channels:
  - conda-forge
dependencies:
  - odfpy
  - ipykernel
  - ploomber >= 0.12.8
  - python-dotenv
  - pyarrow
  - s3fs
  - pandera

  - pip
  - pip:
    - codema-dev-tasks==0.2.0