on_render:
  dotted_path: codema_dev_tasks.hooks.load_environmental_variables
  dotenv_path: ".env"

tasks:

  - source: codema_dev_tasks.requests.fetch_file
    name: download_county_residential_networked_gas_consumption
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2021_09_23_county_residential_networked_gas_consumption.csv
    product: data/external/2021_09_23_county_residential_networked_gas_consumption.csv

  - source: codema_dev_tasks.requests.fetch_file
    name: download_dublin_postal_district_residential_networked_gas_consumption
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2021_09_23_dublin_postal_district_residential_networked_gas_consumption.csv
    product: data/external/2021_09_23_dublin_postal_district_residential_networked_gas_consumption.csv

  - source: codema_dev_tasks.requests.fetch_file
    name: download_county_residential_networked_gas_meters
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2021_09_23_county_residential_gas_meters.csv
    product: data/external/2021_09_23_county_residential_gas_meters.csv

  - source: codema_dev_tasks.requests.fetch_file
    name: download_dublin_postal_district_residential_networked_gas_meters
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2021_09_23_dublin_postal_district_residential_gas_meters.csv
    product: data/external/2021_09_23_dublin_postal_district_residential_gas_meters.csv
      
  - source: codema_dev_tasks.requests.fetch_file
    name: download_synthetic_bers
    params:
      url: s3://codema-dev/views/2021_09_02_dublin_synthetic_building_energy_ratings.parquet
    product: data/external/2021_09_02_dublin_synthetic_building_energy_ratings.parquet

  - source: tasks.create_dublin_postcode_residential_gas_consumption
    product: data/interim/dublin_postcode_residential_networked_gas_consumption.csv

  - source: tasks.create_dublin_postcode_residential_gas_meters
    product: data/interim/dublin_postcode_residential_networked_gas_meters.csv

  - source: tasks.amalgamate_synthetic_ber_gas_consumption_to_postcodes
    product: data/interim/dublin_postcode_synthetic_ber_gas_consumption.csv

  - source: tasks.amalgamate_synthetic_ber_gas_meters_to_postcodes
    product: data/interim/dublin_postcode_synthetic_ber_gas_meters.csv
    
  - source: plot_synthetic_bers_vs_cso_gas.py
    product:
      nb: data/notebooks/plot_synthetic_bers_vs_cso_gas.ipynb
      csv: data/processed/synthetic_bers_vs_cso_gas.csv