tasks:
  
  - source: codema_dev_tasks.requests.fetch_file
    name: download_seai_monitoring_and_reporting
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/raw/2020_01_24_seai_monitoring_and_reporting.xlsx
    product: data/external/2020_01_24_seai_monitoring_and_reporting.xlsx
  
  - source: tasks.save_sheets_as_csvs
    product:
      mprn: data/interim/raw_mprn.csv
      gprn: data/interim/raw_gprn.csv
    
      