name: dbs

channels:
  - conda-forge
  - defaults
  - patrikhlobil # for pandas-bokeh

dependencies:
  - bokeh
  - geopandas
  - pandas
  - pandas-bokeh

  # dev dependencies
  - poetry
  - jupytext
  - ipykernel

  - pip
  pip:
    - berpublicsearch