on_render:
  dotted_path: codema_dev_tasks.hooks.load_environmental_variables
  dotenv_path: ".env"
tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_buildings
    params:
      url: s3://codema-dev/valuation_office_dublin_april_2021.parquet
    product: data/external/valuation_office_dublin_april_2021.parquet
  - source: codema_dev_tasks.requests.fetch_file
    name: download_benchmarks
    params:
      url: s3://codema-dev/benchmarks.csv
    product: data/external/benchmarks.csv
  - source: codema_dev_tasks.requests.fetch_file
    name: download_benchmark_uses
    params:
      url: s3://codema-dev/benchmarks.zip
    product: data/external/benchmarks.zip
  - source: codema_dev_tasks.requests.fetch_file
    name: download_small_area_boundaries
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/dublin_small_area_boundaries_in_routing_keys.gpkg
    product: data/external/dublin_small_area_boundaries_in_routing_keys.gpkg
  