on_render:
  dotted_path: codema_dev_tasks.hooks.load_environmental_variables
  dotenv_path: ".env"
tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_valuation_office_floor_areas_dcc
    params:
      url: s3://codema-dev/raw/2021_06_15_valuation_office_floor_areas_dcc.ods
    product: data/external/2021_06_15_valuation_office_floor_areas_dcc.ods
    
  - source: codema_dev_tasks.requests.fetch_file
    name: download_valuation_office_floor_areas_dlrcc
    params:
      url: s3://codema-dev/raw/2021_06_15_valuation_office_floor_areas_dlrcc.ods
    product: data/external/2021_06_15_valuation_office_floor_areas_dlrcc.ods

  - source: codema_dev_tasks.requests.fetch_file
    name: download_valuation_office_floor_areas_fcc
    params:
      url: s3://codema-dev/raw/2021_06_15_valuation_office_floor_areas_fcc.ods
    product: data/external/2021_06_15_valuation_office_floor_areas_fcc.ods

  - source: codema_dev_tasks.requests.fetch_file
    name: download_valuation_office_floor_areas_sdcc
    params:
      url: s3://codema-dev/raw/2021_06_15_valuation_office_floor_areas_sdcc.ods
    product: data/external/2021_06_15_valuation_office_floor_areas_sdcc.ods

  - source: tasks.concatenate_local_authority_floor_areas
    product: data/interim/raw_dublin_valuation_office_floor_areas.csv