name: electricity-grid
channels:
  - conda-forge
dependencies:
  - ploomber
  - geopandas
  - pandas
  - scikit-learn
  - momepy
  - pyarrow
  - networkx
  
  - pip
  - pip:
    - codema-dev-tasks==0.2.0