meta:
  extract_upstream: False

tasks:
  - source: download.fetch_s3_file
    name: download_small_areas
    params:
      bucket: codema-dev
    product: data/external/dublin_small_area_boundaries_in_routing_keys.gpkg

  - source: group_footprints_by_small_areas.py
    name: group_footprints_by_small_areas
    params:
      small_area_filepath: data/external/dublin_small_area_boundaries_in_routing_keys.gpkg
      urban_atlas_filepath: data/raw/Urban Atlas
    product:
      nb: data/notebooks/group_footprints_by_small_areas.ipynb
      data: data/processed/urban_atlas_small_area_item_area.csv.gz
    upstream: download_small_areas

