name: plot-residential-boiler-stats
channels:
  - conda-forge
  - patrikhlobil
dependencies:
  - geopandas
  - ploomber
  - pandas-bokeh
  - python-dotenv
  - pyarrow
  - pip
  - pip:
    - codema-dev-tasks==0.1.0
