name: hdd
channels:
  - conda-forge
  - patrikhlobil
dependencies:
  - python
  - pandas
  - pandas-bokeh
  - geopandas
  - prefect
  - fsspec
  - s3fs
  - pyarrow
  - python-dotenv
  - jupyter
  - papermill
  - jupytext
  - selenium
  - geckodriver
  - dataframe-image