on_render:
  dotted_path: codema_dev_tasks.hooks.load_environmental_variables
  dotenv_path: ".env"
tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_synthetic_bers
    params:
      url: s3://codema-dev/views/2021_09_02_dublin_synthetic_building_energy_ratings.parquet
    product: data/external/2021_09_02_dublin_synthetic_building_energy_ratings.parquet
  
  - source: codema_dev_tasks.requests.fetch_file
    name: download_valuation_office_energy_estimates
    params:
      url: s3://codema-dev/views/2021_09_24_dublin_valuation_office_energy_estimates.csv
    product: data/external/2021_09_24_dublin_valuation_office_energy_estimates.csv

  - source: codema_dev_tasks.requests.fetch_file
    name: download_public_sector_demands
    params:
      url: s3://codema-dev/views/2021_09_27_seai_monitoring_and_reporting_buildings_dublin.csv
    product: data/external/2021_09_27_seai_monitoring_and_reporting_buildings_dublin.csv
  
  - source: codema_dev_tasks.requests.fetch_file
    name: download_epa_industrial_site_demands
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2019_10_14_epa_industrial_site_demands.csv
    product: data/external/2019_10_14_epa_industrial_site_demands.csv

  - source: codema_dev_tasks.requests.fetch_file
    name: download_dublin_small_area_boundaries
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2021_08_12_dublin_small_area_boundaries.gpkg
    product: data/external/2021_08_12_dublin_small_area_boundaries.gpkg

  - source: estimate_heat_demand_density.py
    product:
      nb: data/notebooks/estimate_heat_demand_density.ipynb
      density: data/processed/small_area_heat_demand_density.csv
      demand: data/processed/small_area_heat_demand.csv