name: lv
channels:
  - conda-forge
dependencies:
  - pyarrow
  - pandas
  - prefect
  - python-dotenv
  - pygraphviz

  # dev
  - black
  - mypy
  - ipython
  
  - pip
  - pip:
    - prefect-geopandas-serializer