name: line-lengths
channels:
  - conda-forge
dependencies:
  - prefect
  - geopandas
  - pyarrow
  - python-dotenv
  - graphviz
  - pip
  - pip:
    - prefect-geopandas-serializer
    - graphviz # python engine for graphviz