name: estimate-dublin-residential-building-characteristics
channels:
  - conda-forge
dependencies:
  - ploomber
  - aiohttp
  - fsspec
  - tqdm
  - requests
  - pandas
  - pyarrow
  - dask
  
  - pip
  - pip:
    - codema-dev-tasks==0.2.0