name: estimate-dublin-residential-building-characteristics
channels:
  - conda-forge
dependencies:
  - ploomber
  - aiohttp
  - fsspec
  - pip
  - tqdm
  - requests
  - pip:
    - codema-dev-tasks==0.2.0