tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_census_building_ages
    params:
      url: https://codema-dev.s3.eu-west-1.amazonaws.com/views/2021_10_06_ireland_census_individual_buildings_inferred_period_built.zip
    product: data/external/2021_10_06_ireland_census_individual_buildings_inferred_period_built.zip
  
  - source: tasks.download_building_energy_ratings
    product: data/external/BERPublicsearch.zip
  