name: retrofit
channels:
  - conda-forge
dependencies:

  # fugue dependencies
  - pandas
  - pyarrow
  - sqlalchemy
  - dask
  
  # qpd dependencies
  - antlr4-python3-runtime
  - ciso8601
  - fs

  - pip
  - pip:
    - fugue