on_render:
  dotted_path: codema_dev_tasks.hooks.load_environmental_variables
  dotenv_path: ".env"
tasks:
  - source: codema_dev_tasks.requests.fetch_file
    name: download_buildings
    params:
      url: s3://codema-dev/dublin_census_2016_filled_with_ber_public_14_05_2021.parquet
    product: data/external/dublin_census_2016_filled_with_ber_public_14_05_2021.parquet
  - source: tasks.load_defaults
    product: data/interim/defaults.json
  - source: tasks.replace_uvalues_with_target_uvalues
    product: data/processed/2021_05_retrofitted_uvalues.csv
  - source: tasks.estimate_individual_building_retrofit_costs
    product: data/processed/2021_05_individual_building_retrofit_costs.csv
  - source: tasks.estimate_small_area_retrofit_costs
    product: data/processed/2021_05_small_area_retrofit_costs.csv
  - source: tasks.estimate_individual_building_retrofit_energy_saving
    product: data/processed/2021_05_ber_energy_saving_after_targets_no_rebound.csv